/*Charles Winters
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package configurator;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.geom.Line2D;
import java.io.*;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;

/**
 *
 *
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        newVm = new javax.swing.JButton();
        newHub = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        consoleLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        hubPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        fileChooser.setDialogTitle("Open a configuration file...");
        fileChooser.setFileFilter(new configFilter());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(775, 500));
        setPreferredSize(new java.awt.Dimension(775, 500));

        newVm.setText("New VM");
        newVm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newVmActionPerformed(evt);
            }
        });

        newHub.setText("New Hub");
        newHub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newHubActionPerformed(evt);
            }
        });

        jLabel1.setText("Console:");

        jScrollPane1.setHorizontalScrollBar(null);

        mainPanel.setPreferredSize(new java.awt.Dimension(345, 0));
        mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.Y_AXIS));

        hubPanel.setMaximumSize(new java.awt.Dimension(350, 32767));
        hubPanel.setPreferredSize(new java.awt.Dimension(345, 0));
        hubPanel.setLayout(new javax.swing.BoxLayout(hubPanel, javax.swing.BoxLayout.Y_AXIS));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(hubPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(hubPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        saveAsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAsMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveAsMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        aboutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jScrollPane1)
                                                .addContainerGap())
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(consoleLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(newVm)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(newHub)
                                                .addGap(0, 613, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(newVm)
                                        .addComponent(newHub))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(consoleLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
        );

        pack();
    }// </editor-fold>

    HashMap<String, VM> vmMap = new HashMap<>();
    HashMap<String, Hub> hubMap = new HashMap<>();
    HashMap<String, JButton> buttonsMap = new HashMap<>();
    ImageIcon vmIcon = new javax.swing.ImageIcon(getClass().getResource("/configurator/images/vm.jpg"));
    ImageIcon hubIcon = new javax.swing.ImageIcon(getClass().getResource("/configurator/images/hub.jpg"));

    public void createNetItem(String type, String name) {
        switch (type) {
            case "vm":
            {
                //create new VM by name, put in hashmap, and publish button to main window
                VM item = new VM(name);
                vmMap.put(name, item);
                publishItem(item);
                this.setConsole("VM " + name + " created successfully.");
                break;
            }
            case "hub":
            {
                //create new hub by name, put in hashmap, and publish button to main window
                Hub item = new Hub(name);
                hubMap.put(name, item);
                publishItem(item);
                this.setConsole("Hub " + name + " created successfully.");
                break;
            }
            default:
                //if not vm or hub, error out and move on
                System.out.println("Invalid item type. Should be vm or hub.");
                break;
        }
    }

    public void publishItem(VM item) {
        //publish the VM to the page via a clickable JButton
        JButton button = new JButton(item.name);
        button.setVerticalTextPosition(SwingConstants.BOTTOM);
        button.setHorizontalTextPosition(SwingConstants.CENTER);
        button.setAlignmentX(Component.CENTER_ALIGNMENT);
        buttonsMap.put(item.name, button);
        VM net = vmMap.get(item.name);
        MainWindow main = this;

        //add action listener to click to pull up VMEditWindow
        button.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                //System.out.println(net.name);
                VMEditWindow editor = new VMEditWindow(main);
                editor.changeName(net.name); editor.changeOs(net.os);
                editor.changeVer(net.ver); editor.changeSrc(net.src);
                editor.changeEth0(net.eth0); editor.changeEth1(net.eth1);
                editor.changeEth2(net.eth2);
                editor.setNetItem(net);
                editor.setVisible(true);
            }
        });
        button.setIcon(vmIcon);
        mainPanel.add(button);
        mainPanel.revalidate();
        validate();
    }

    public void publishItem(Hub item) {
        //publish Hub to window via a JButton
        JButton button = new JButton(item.name);
        button.setVerticalTextPosition(SwingConstants.BOTTOM);
        button.setHorizontalTextPosition(SwingConstants.CENTER);
        button.setAlignmentX(Component.CENTER_ALIGNMENT);
        buttonsMap.put(item.name, button);
        Hub net = hubMap.get(item.name);
        MainWindow main = this;

        //add action listener to click to pull up HubEditWindow
        button.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e){
                HubEditWindow editor = new HubEditWindow(main);
                editor.changeName(net.name); editor.changeInf(net.inf);
                editor.changeSubnet(net.subnet); editor.changeMask(net.netmask);
                editor.setNetItem(net);
                editor.setVisible(true);
            }
        });
        button.setIcon(hubIcon);
        hubPanel.add(button);
        hubPanel.revalidate();
        validate();
    }

    public boolean deleteItem (String name) {
        //properly delete a network item based on name
        if (vmMap.get(name) != null) { //check if it is a hub
            for (Hub hub : hubMap.values()) {
                hub.removeVM(name);
            }
            mainPanel.remove(buttonsMap.get(name));
            mainPanel.revalidate();
            mainPanel.repaint();
            vmMap.remove(name);
            this.setConsole(name + " has been removed successfully.");
            return true;
        } else if (hubMap.get(name) != null) { //check if it is a hub
            for (VM vm : vmMap.values()) {
                vm.removeHub(hubMap.get(name).getInternal());
            }
            mainPanel.remove(buttonsMap.get(name));
            mainPanel.revalidate();
            mainPanel.repaint();
            hubMap.remove(name);
            this.setConsole(name + " has been removed successfully.");
            return true;
        } else { //item not found
            this.setConsole("That network item doesn't exist!");
            return false;
        }
    }

    public void connectAll() {
        //connect all vms and hubs using the solution string when parsing an open file
        System.out.println("connectall called");
        for (VM vm : vmMap.values()) {
            HashMap<String, String> conns = vm.connections;
            for (String s : conns.values()) {
                s = s.substring(3);
                for (Hub hub : hubMap.values()) {
                    if (hub.internal.equals(s)) {
                        connectItems(vm.name, hub.name);
                    }
                }
            }
        }
    }

    public void connectItems(String vm, String hub) {
        //connect a vm to a hub based on name
        JButton buttonVM = buttonsMap.get(vm);
        JButton buttonHub = buttonsMap.get(hub);

        connect(buttonVM.getLocation(), buttonHub.getLocation());
        System.out.println("connectitems called");
    }

    public void connect(Point one, Point two) {
        //draw the line to visually show the connection between vm and hub
        Graphics g = mainPanel.getGraphics();
        int x1 = (int) Math.round(one.getX()) + 50;
        int y1 = (int) Math.round(one.getY()) + 50;
        int x2 = (int) Math.round(two.getX()) + 400;
        int y2 = (int) Math.round(two.getY()) + 50;
        g.drawLine(x1, y1, x2, y2);
        System.out.println("connect called");
    }

    public void setConsole(String text) {
        //method to set the user facing console text to the input string
        consoleLbl.setText(text);
    }

    public HashMap<String, VM> getVmItems() {
        return vmMap;
    }

    public HashMap<String, Hub> getHubItems() {
        return hubMap;
    }

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        // open option clicked in file window
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try {
                // parse the chosen file
                Parser parser = new Parser(new FileReader(file.getAbsolutePath()));

                vmMap = parser.getVmMap();
                hubMap = parser.getHubMap();

                for (VM item : vmMap.values()) {
                    publishItem(item);
                }
                for (Hub item : hubMap.values()) {
                    publishItem(item);
                }
                this.connectAll();
                this.setConsole("File opened successfully.");
            } catch (IOException ex) {
                System.out.println("problem accessing file " + file.getAbsolutePath());
            }
        } else {
            //user cancels open file dialog
            System.out.println("File access cancelled by user.");
        }
    }

    private void newVmActionPerformed(java.awt.event.ActionEvent evt) {
        //click new VM, asks for name and creates it
        JFrame frame = new JFrame("Create a new vm");
        String name = JOptionPane.showInputDialog(frame, "Enter a name:");
        consoleLbl.setText("");
        if (name != null && !name.equals("")){
            name = name.replaceAll("\\s+","");
            if (vmMap.get(name) != null) {
                consoleLbl.setText("ERROR - network item with that name already exists!");
            } else {
                createNetItem("vm", name);
            }
        }
    }

    private void newHubActionPerformed(java.awt.event.ActionEvent evt) {
        //click on new hub, asks for name and creates it
        JFrame frame = new JFrame("Create a new hub");
        String name = JOptionPane.showInputDialog(frame, "Enter a name:");
        consoleLbl.setText("");
        if (name != null && !name.equals("")){
            name = name.replaceAll("\\s+","");
            if (hubMap.get(name) != null) {
                consoleLbl.setText("ERROR - network item with that name already exists!");
            } else {
                createNetItem("hub", name);
            }
        }
    }

    private void aboutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        //about menu option, displays group info
        JFrame frame = new JFrame("About Configurator");
        String aboutString =
                "Test 1 cset3600\n";
        JOptionPane.showMessageDialog(frame, aboutString);
    }

    private void saveAsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {
        //write config file based on current data in program
        Writer writer = new Writer();
        String finalstr;
        finalstr = "";

        int returnVal = fileChooser.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();

            //generate string for every VM, add to main string
            for (VM item : vmMap.values()) {
                finalstr += item.generateString();
            }
            //generate string for every hub, add to main string
            for (Hub item : hubMap.values()) {
                finalstr += item.generateString();
            }
            finalstr += "partial_solution {\n";
            //add string containing solutions/connections for all VMs
            for (VM item : vmMap.values()) {
                finalstr += item.getSolutionString();
            }
            if (finalstr.charAt(finalstr.length()-2)==',') {
                finalstr = finalstr.substring(0, finalstr.length()-2);
            }
            //write ending curly braces to complete .cfg syntax
            finalstr += "\n}\n";

            try {
                configurator.Writer.writeCfg(finalstr, new File(file.getAbsolutePath() ));
                this.setConsole("File saved.");
            } catch (IOException ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            System.out.println("File access cancelled by user.");
        }


    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JLabel consoleLbl;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JPanel hubPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JButton newHub;
    private javax.swing.JButton newVm;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    // End of variables declaration

}
